/** @type {import('jest').Config} */
module.exports = {
  testEnvironment: "node",
  roots: ["<rootDir>/tests"],
  testMatch: ["**/*.test.js", "**/*.spec.js"],
  collectCoverage: true,
  coverageDirectory: "coverage",
  verbose: true,
};
// jest-config-extension 1: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 2: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 3: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 4: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 5: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 6: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 7: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 8: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 9: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 10: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 11: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 12: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 13: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 14: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 15: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 16: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 17: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 18: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 19: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 20: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 21: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 22: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 23: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 24: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 25: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 26: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 27: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 28: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 29: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 30: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 31: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 32: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 33: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 34: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 35: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 36: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 37: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 38: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 39: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 40: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 41: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 42: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 43: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 44: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 45: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 46: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 47: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 48: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 49: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 50: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 51: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 52: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 53: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 54: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 55: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 56: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 57: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 58: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 59: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 60: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 61: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 62: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 63: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 64: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 65: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 66: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 67: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 68: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 69: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 70: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 71: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 72: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 73: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 74: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 75: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 76: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 77: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 78: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 79: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 80: 本节为基础设施标准化补充说明，用于团队执行一致性。
// jest-config-extension 81: 本节为基础设施标准化补充说明，用于团队执行一致性。
