replicaCount: 1

image:
  repository: liuhongke985/ai-governance
  pullPolicy: IfNotPresent
  tag: "poC"

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 500m
    memory: 1024Mi
  limits:
    cpu: 2000m
    memory: 8Gi

env: {}

nodeSelector: {}
tolerations: []
affinity: {}
